// ACTION TYPES
export enum IdsAcciones {
  TAREAS_AGREGAR = "TAREAS/AGREGAR",
  TAREAS_FILTRAR = "TAREAS/FILTRAR",
  TAREAS_MARCAR_TODAS = "TAREAS/MARCAR_TODAS",
  TAREAS_ELIMINAR_FINALIZADAS = "TAREAS/ELIMINAR_FINALIZADAS",
  TAREA_CAMBIAR_ESTADO = "TAREA/CAMBIAR_ESTADO",
  TAREA_EDITAR = "TAREA/EDITAR",
  TAREA_ELIMINAR = "TAREA/ELIMINAR",
  TAREA_MOVER = "TAREA/MOVER",
  __WARN_DEFAULT = "NO_UTILIZAR/ESTO_ES_SOLO_POR_INTEROP",
}
